public class Day1 {
/*

1. creating a apex class (vscode):
ctrl+sft+p -> search for create apex class -> provide className

2. create apex class (setup menu):
setup-> apex classes -> new -> save

3. create apex class (from developer console) :
file ->new -> apex class -> give class name -> press enter




MVC -> MOdel View Controller


model (database) -> object
VIew (User interface) -> tabs, page layouts, compact layouts, flexi pages
controller (business logic) -> apex 

data type -> 
    1.primitive : (fundamental data types) :
    fixed length of memory (static memory allocation)
`
    1.string: (text data)
    string datatype allows us to store alphanumerical values along with special
    chracters
    note: (text area, picklist, multi picklist, text area rich, email , phone ,url, fields will refer to string datatype by default)

    2. integer: (number except decimal point)
    3.decimal : (number with decimal point)
    4.long : (large numbers)
    5.boolean : (checkbox[true/false])
    6.date  : (to store a da
    te)
    7. time data type : it allows us to store 12/24 hours time value inside variable
    ex. 10:00 AM, 22:33:980
    8.datetime :(timestamp)
    9.BLOB (Binary large objects) : this datatype is used to store binary files (pictures/images/video/audio)
    
    note : store upto 2GB, 
    10.ID : (15/18 character salesforce ID)


    2.non primitive : (sobject -> salesforce object):
    dynamic memory allocation
*/
}